### PR TITLE
bug(subgraph): Make Rewards sortable, sort them in explorer

### LINKED ISSUE #381: Missed reward calls are being inaccurately represented for some transcoders
**Describe the bug (required)**
There are a few transcoders who missed a reward call over the past 30 rounds but their missed reward call count is incorrectly being displayed as 0. For example, transcoder `0x481efb669b423cfaffa49890205427dea9b3d693` missed a reward call during round 1309 but the explorer shows a missed reward call total of 0.

**Expected behavior (required)**
If a transcoder missed reward calls during the past 30 rounds it should be accurately reflected in the missed reward call column.

**Additional context (optional)**
This issue seems to have been introduced when we upgraded our Graph Node. The currrent Graph Node version now paginates results, displaying a maximum of 100 results per request. Because rounds are not returned in order when querying the subgraph, if a transcoder has been active for more than 100 rounds, the explorer ends up displaying a set of 30 reward calls that are not necessarily representative of last 30 rounds. To see for yourself, run [this graphql query](https://graph.livepeer.org/subgraphs/name/livepeer/graphql?query=%7B%0A%20%20transcoder(id%3A%20%220x481efb669b423cfaffa49890205427dea9b3d693%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20active%0A%20%20%20%20rewards%20%7B%0A%20%20%20%20%20%20rewardTokens%0A%20%20%20%20%20%20round%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) on our subgraph.

### PR DESCRIPTION
**Pull request by iameli**
**What does this pull request do? Explain your changes. (required)**
Allows for reward rounds to be sorted, and presents them as sorted in the explorer.

**Specific updates (required)**

- Changes the subgraph's `Reward` entity to be naturally sortable by round ID. Sorts it descending in the explorer so we properly query for the most recent rounds.

Rewards now have ids of the form `${transcoderId}, ${leftPad(roundNumber, 40)}` such that the natural ASCII ordering is the same as the numerical round ordering.

40 digits is a pretty absurd number of rounds but that's probably okay.

**How did you test each of these updates (required)**
This branch is deployed on a separate subgraph, it's still syncing but the change appears to be working: https://graph.livepeer.org/subgraphs/name/reward-sorting/graphql?query=%7B%0A%20%20transcoder(id%3A%20%220x481efb669b423cfaffa49890205427dea9b3d693%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20active%0A%20%20%20%20rewards%20(orderBy%3Aid%2C%20orderDirection%3Adesc)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rewardTokens%0A%20%20%20%20%20%20round%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

**Does this pull request close any open issues?**
Fixes #381

### CODE REVIEW

**Review by adamsoffer — APPROVED** [review]
Left pad FTW! Nice one. LGTM 🚢

**Comment by adamsoffer** [comment]
> Left pad FTW! Nice one. LGTM 🚢

Actually, one thing. Make sure to add a left pad to `rewardId` inside `bondingManager.ts` as well, otherwise `rewardTokens` will always be `null`. 

https://github.com/livepeer/livepeerjs/blob/eli/reward-sorting/packages/subgraph/mappings/bondingManager.ts#L190

**Comment by iameli** [comment]
@adamsoffer Fixed; refactored to be in a helper since it's used in more than one place. Also took the opportunity to bump subgraph to 0.9.0... I should make sure the server-side is too, come to think of it.

**Comment by adamsoffer** [comment]
@iameli Nice. Looks solid 👌

**Pull request merged**
