### PR TITLE
add team and jobs to .com

### PR DESCRIPTION
**Pull request by adamsoffer**
**What does this pull request do? Explain your changes. (required)**
This PR adds a /team and /jobs page to livepeer.com since we're no longer featuring these things on the new .org. All content is editable via the CMS. These pages will be redesigned in the near time by Basement with the team page being combined with a future "about" page.

This PR also cleans up the styles on the documentation and sign up pages to better match the original design. 

**Screenshots (optional):**

## Jobs page
Screen Shot 2020-07-20 at 9 46 44 AM

## Jobs detail page
Screen Shot 2020-07-20 at 9 47 16 AM

## Team page
Screen Shot 2020-07-20 at 9 47 35 AM

## Docs page
Screen Shot 2020-07-20 at 9 47 52 AM

## Register
Screen Shot 2020-07-20 at 9 52 54 AM

### CODE REVIEW

**Comment by adamsoffer** [comment]
@iameli @wohlner okay to merge?

**Review by iameli — APPROVED** [review]
LGTM!

**Comment by adamsoffer** [comment]
@iameli just rebased on master. Build failing but not sure why. Any idea?

**Comment by iameli** [comment]
@adamsoffer Looks like this

```
▶ npx now logs livepeer-monster-2x9b24a6y.vercel.app
> UPDATE AVAILABLE Run `yarn add now@latest` to install Now CLI 19.2.0
> Changelog: https://github.com/zeit/now/releases/tag/now@19.2.0
Now CLI 17.1.1
> Fetched deployment "livepeer-monster-2x9b24a6y.vercel.app" in iameli1 [342ms]
2020-07-24T19:29:26.009Z                   from /vercel/.node-gyp/12.16.2/include/node/node.h:67,
2020-07-24T19:29:26.009Z                   from ../../nan/nan.h:56,
2020-07-24T19:29:26.009Z                   from ../src/node-boilerplate/scrypt_params_async.cc:1:
2020-07-24T19:29:26.009Z  /vercel/.node-gyp/12.16.2/include/node/v8.h:3499:22: note: declared here
2020-07-24T19:29:26.009Z                   bool Set(Local<Value> key, Local<Value> value));
2020-07-24T19:29:26.009Z                        ^
2020-07-24T19:29:26.009Z  /vercel/.node-gyp/12.16.2/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
2020-07-24T19:29:26.009Z     declarator __attribute__((deprecated(message)))
2020-07-24T19:29:26.009Z     ^~~~~~~~~~
2020-07-24T19:29:26.009Z  ../src/node-boilerplate/scrypt_params_async.cc:32:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
2020-07-24T19:29:26.009Z     callback->Call(2, argv);
2020-07-24T19:29:26.009Z                           ^
2020-07-24T19:29:26.009Z  In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
2020-07-24T19:29:26.009Z  ../../nan/nan.h:1742:3: note: declared here
2020-07-24T19:29:26.010Z     Call(int argc, v8::Local<v8::Value> argv[]) const {
2020-07-24T19:29:26.010Z     ^~~~
2020-07-24T19:29:26.010Z  make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
2020-07-24T19:29:26.010Z  gyp ERR! build error
2020-07-24T19:29:26.010Z  gyp ERR! stack Error: `make` failed with exit code: 2
2020-07-24T19:29:26.010Z  gyp ERR! stack     at ChildProcess.onExit (/vercel/7bdfc057/node_modules/libnpm/node_modules/node-gyp/lib/build.js:262:23)
2020-07-24T19:29:26.010Z  gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
2020-07-24T19:29:26.010Z  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2020-07-24T19:29:26.010Z  gyp ERR! System Linux 4.14.177-139.254.amzn2.x86_64
2020-07-24T19:29:26.010Z  gyp ERR! command \"/node12/bin/node\" \"/vercel/7bdfc057/node_modules/.bin/node-gyp\" \"rebuild\"
2020-07-24T19:29:26.010Z  gyp ERR! cwd /vercel/7bdfc057/node_modules/scrypt
2020-07-24T19:29:26.010Z  gyp ERR! node -v v12.16.2
2020-07-24T19:29:26.010Z  gyp ERR! node-gyp -v v4.0.0
2020-07-24T19:29:26.010Z  gyp ERR! not ok"
2020-07-24T19:29:26.010Z  info This module is OPTIONAL, you can safely ignore this error
2020-07-24T19:29:32.700Z  Done in 166.60s.
2020-07-24T19:29:32.737Z  Running "yarn run now-build"
2020-07-24T19:29:32.902Z  yarn run v1.22.4
2020-07-24T19:29:32.944Z  $ yarn run build
2020-07-24T19:29:33.151Z  $ sanity build
2020-07-24T19:29:56.305Z
2020-07-24T19:29:56.305Z  Error: Errors while building:
2020-07-24T19:29:56.305Z  ./schemas/schema.js?sanityPart=part%3A%40sanity%2Fbase%2Fschema
2020-07-24T19:29:56.305Z  Module not found: Error: Can't resolve './objects/jobsSection' in '/vercel/7bdfc057/packages/livepeer.com/admin/schemas'
2020-07-24T19:29:56.305Z  resolve './objects/jobsSection' in '/vercel/7bdfc057/packages/livepeer.com/admin/schemas'
2020-07-24T19:29:56.305Z    using description file: /vercel/7bdfc057/packages/livepeer.com/admin/package.json (relative path: ./schemas)
2020-07-24T19:29:56.305Z      Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.305Z    after using description file: /vercel/7bdfc057/packages/livepeer.com/admin/package.json (relative path: ./schemas)
2020-07-24T19:29:56.305Z      using description file: /vercel/7bdfc057/packages/livepeer.com/admin/package.json (relative path: ./schemas/objects/jobsSection)
2020-07-24T19:29:56.305Z        no extension
2020-07-24T19:29:56.305Z          Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.305Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection doesn't exist
2020-07-24T19:29:56.305Z        .js
2020-07-24T19:29:56.305Z          Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.305Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.js doesn't exist
2020-07-24T19:29:56.305Z        .jsx
2020-07-24T19:29:56.305Z          Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.305Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.jsx doesn't exist
2020-07-24T19:29:56.305Z        .es6
2020-07-24T19:29:56.305Z          Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.305Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.es6 doesn't exist
2020-07-24T19:29:56.305Z        .es
2020-07-24T19:29:56.305Z          Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.306Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.es doesn't exist
2020-07-24T19:29:56.306Z        .mjs
2020-07-24T19:29:56.306Z          Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.306Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.mjs doesn't exist
2020-07-24T19:29:56.306Z        .ts
2020-07-24T19:29:56.306Z          Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.306Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.ts doesn't exist
2020-07-24T19:29:56.306Z        .tsx
2020-07-24T19:29:56.306Z          Field 'browser' doesn't contain a valid alias configuration
2020-07-24T19:29:56.306Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.tsx doesn't exist
2020-07-24T19:29:56.306Z        as directory
2020-07-24T19:29:56.306Z          /vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection doesn't exist
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection]
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.js]
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.jsx]
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.es6]
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.es]
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.mjs]
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.ts]
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection.tsx]
2020-07-24T19:29:56.306Z  [/vercel/7bdfc057/packages/livepeer.com/admin/schemas/objects/jobsSection]
2020-07-24T19:29:56.306Z   @ ./schemas/schema.js?sanityPart=part%3A%40sanity%2Fbase%2Fschema 62:42-74
2020-07-24T19:29:56.306Z   @ /vercel/7bdfc057/node_modules/@sanity/default-layout/lib/components/SchemaErrorReporter.js
2020-07-24T19:29:56.306Z   @ /vercel/7bdfc057/node_modules/@sanity/default-layout/lib/components/DefaultLayout.js
2020-07-24T19:29:56.306Z   @ /vercel/7bdfc057/node_modules/@sanity/default-layout/lib/components/DefaultLayoutContainer.js?sanityPart=part%3A%40sanity%2Fbase%2Froot
2020-07-24T19:29:56.306Z   @ /vercel/7bdfc057/node_modules/@sanity/base/lib/components/SanityRoot.js?sanityPart=part%3A%40sanity%2Fbase%2Fsanity-root
2020-07-24T19:29:56.306Z   @ /vercel/7bdfc057/node_modules/@sanity/server/lib/browser/entry.js
2020-07-24T19:29:56.306Z   @ multi /vercel/7bdfc057/node_modules/normalize.css/normalize.css /vercel/7bdfc057/node_modules/@sanity/server/lib/browser/entry.js
2020-07-24T19:29:56.306Z      at ~/7bdfc057/node_modules/@sanity/core/lib/actions/build/buildStaticAssets.js:129:15
2020-07-24T19:29:56.306Z      at Generator.next (<anonymous>)
2020-07-24T19:29:56.306Z      at asyncGeneratorStep (~/7bdfc057/node_modules/@sanity/core/lib/actions/build/buildStaticAssets.js:40:103)
2020-07-24T19:29:56.306Z      at _next (~/7bdfc057/node_modules/@sanity/core/lib/actions/build/buildStaticAssets.js:42:194)
2020-07-24T19:29:56.351Z  error Command failed with exit code 1.
2020-07-24T19:29:56.351Z  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-07-24T19:29:56.368Z  error Command failed with exit code 1.
2020-07-24T19:29:56.368Z  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-07-24T19:29:56.376Z  Error: Command "yarn run now-build" exited with 1
2020-07-24T19:29:57.917Z  Build completed. Populating build cache...
2020-07-24T19:29:57.959Z  Running packages/livepeer.com/www/package.json builder.exports.prepareCache...
2020-07-24T19:29:58.641Z  Uploading build cache [2.41 MB]...
2020-07-24T19:29:58.778Z  Build cache uploaded: 136.693ms
2020-07-24T19:29:58.787Z  Done with "packages/livepeer.com/www/package.json"
2020-07-24T19:29:59.118Z  Done with "packages/livepeer.com/admin/package.json"
```

**Comment by adamsoffer** [comment]
Fixed the build. Thanks @iameli!

**Pull request merged**
