### PR TITLE
crypto.livepeer.tv Channel for ETH startups

### PR DESCRIPTION
**Pull request by Matlemad**
Hello Folks! simple idea.

we crew from Livepeer.tv in Berlin are receiving a lot of requests from ETH Community Startups
to stream their Meetups etc. Some also want us to fly to other destinations to do it.
So I believe this is a demand that LP could help solving.

LP.tv Berlin has a second channel called Crypto.livepeer.tv

I think it would an awesome thing to get ETH startups to use crypto.livepeer.tv
as a dedicated channel for their happenings and livestreams. In a perfect scenario, every startup within the ETH community will have a www.startup.io/livestream section on their website, where an embedded Crypto.livepeer.tv runs non-stop. Sponsoring each others, directly website to website
without passing through YT.

a Calendar for Crypto.livepeer.tv?
1) book a slot feature
2) login/txn to prove identity
3) disclaimer "LP is not responsible for malicious content/third party violations etc" 
4) release of a Stream key valid for a specific time only.

LG xx
Mat

**What does this pull request do? Explain your changes. (required)**
Create a login/identity/calendar based system for crypto.livepeer.tv
in order to make the channel available to Crypto Startups to stream their happenings directly.

**Specific updates (required)**
crypto.livepeer.tv/Bookaslot sub-page
calendar page
fill-in fields with company, email contact etc.
automatic system/txn to prove identity

**How did you test each of these updates (required)**
I'm not a dev

**Does this pull request close any open issues?**
no

**Screenshots (optional):**

**Checklist:**

- [ x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by RaffiSapire** [comment]
Hey there,

Yes indeed that is the idea for Crypto.Livepeer.tv! Awesome that projects
are paying you to fly out too. There is a separate calendar for
Crypto.livepeer.tv, and its here:
https://calendar.google.com/calendar/embed?src=livepeer.org_7p9cr4j343rla039ev8d4pu78s%40group.calendar.google.com&ctz=America%2FNew_York

Content is solely crypto - related, and projects including Status,
CryptoNYC, Truebit Art project, Aragon, Decentraland etc have been on
there, running their own town halls, conferences/meetups, or doing
interviews with us.

I just shared the calendar with you, and Chris has permissions to schedule
events on there. Maybe you could create a google form page that sends sign
ups directly to Chris' inbox so he can add the events and manage any
overlap? We also use it here in NYC, so I'll make sure we add any dates
we're using it so as not to overlap.

Raffi
ᐧ

**Comment by Matlemad** [comment]
Hey Raffi, thanks a lot! I was aware there was already a calendar for Crypto. :)

What I have in mind is actually something **more designed and more articulated** on the architecture side, that's the reason why I opened a Pull Request :P 

a **GOOGLE CALENDAR** has some some limitations,
the first of many being that **someone has to take care of it**,
and organise it/resolve/contact the applicants if there are irregularities in the booking or in proving Identity.

The best scenario would be to have a crypto.livepeer.tv PAGE
with the player on top (+ embedding code)
and the infos and link to booking form right below.

**BOOKING FORM**
Let me link you to an example I bumped into recently, as I'm looking for venues for a tour in September.
http://www.theearlybird.at/at/en/booking
it's a bar in Innsbruck, Austria, they have this clear (but in German!) form where they lead you through the rules of the self booking, and at the end there's a calendar widget that shows the availabilities.
I believe that in our case this very last part could definitely be connected to the already existent Google Calendar for Crypto. And allows LP to disclaim any responsibility on the content side.

**ID verification** 
we might still need a certain degree of human verification to make sure that behind e.g. StartupXYZ there is a active startup, member of the ETH Community (and not villains).
But I also think that **a simple transaction** could solve the ID problem.
Maybe the StartupXYZ could be asked to do a gas txn, copy the txn number somewhere (on their website?) as a stamp?

**Temporary Stream Key**
This is, I suppose, the most tricky part.
So, once the whole booking and ID verification is accomplished, Crypto should release **privately and securely** a streaming key that allows the applicant to access to Crypto.livepeer.tv for the reserved slot and proceed to stream their Meetup (if the stream happens 18:00 to 20:00, it's suggested to reserve 19:00 to 21:00)

Let me know if it makes more sense.
Hugs!
M

**Comment by ericxtang** [comment]
@Matlemad who worked on this PR?  I see a lot of ENS integrations - want to understand what's happening here.

**Comment by Matlemad** [comment]
@ericxtang I see a lot of contributions too, but handling them is unfortunately beyond my knowledge.
I've only translated what I saw as a need and a desire from many actors in the ETH and BC community
to use Livepeer instead of YT, and proposed a temporary quick solution to get these people sharing and determining the palimpsest of crypto.livepeer.tv in an autonomous way.

Please let me know how I can help further!
xM

**Comment by saskakol** [comment]
@Matlemad If this is a proposal, shouldn't this be an issue rather than a pull request, since PRs are used to submit changes to the project? To me it looks like the changes here are made to support ENS names in the player and explorer, but i thought those changes were merged already.

**Comment by Matlemad** [comment]
@iSasFTW yes I know and... my bad. Shall I move it into Issues?

**Comment by saskakol** [comment]
@Matlemad Yeah, that might be a good idea for the sake of clarity. We can continue the discussion over there.

I guess this PR can be closed now. I'm not a 100% sure, but i have a feeling that these changes have already been merged in a previous pull request a while back, and if that's the case this issue isn't needed anymore.

**Comment by Matlemad** [comment]
Yop! and sorry for the confusion created!

**Pull request closed without merging**
