### PR TITLE
add livepeer.com package

### PR DESCRIPTION
**Pull request by adamsoffer**
**What does this pull request do? Explain your changes. (required)**
This PR introduces the livepeer.com package to the monorepo. 

**Specific updates (required)**
- introduces a new package called `livepeer.com`
- updates lerna.json file in root of project to support nested tree of packages since the package includes two sub packages (`www` and `admin`)

### CODE REVIEW

**Review by iameli — COMMENTED** [review]
Hmm. I'm not opposed to nesting the two monorepos if we have to, but would it not be simpler to flatten them into one big one? Nothing wrong with putting the `now.json` file into the top level file and pointing it at something like `packages/livepeer-admin` and `packages/livepeer-www` or something.

**Comment by adamsoffer** [comment]
> Hmm. I'm not opposed to nesting the two monorepos if we have to, but would it not be simpler to flatten them into one big one? Nothing wrong with putting the `now.json` file into the top level file and pointing it at something like `packages/livepeer-admin` and `packages/livepeer-www` or something.

@iameli Yeah, we can flatten and move now.json to the root. If we do that, it would make sense to combine the now.json config inside the explorer-2.0 repo as well. I currently have it set up as one now.json file per project. Do you want to create a separate issue to "flatten" mono-repo with shared now.json config so I'm not blocking you? This might take me a little bit to configure properly.

**Comment by adamsoffer** [comment]
I suppose one nice property of one `now.json` per project is the separation of concerns. A single now.json at the root could potentially become quite large over time as new projects are introduced to the monorepo. 🤷‍♂️

**Comment by adamsoffer** [comment]
Okay yeah after looking into it some more I think it's more practical to keep as is for now. Moving `now.json` to the root would mess up the git integrations I set up with Now.

**Review by iameli — APPROVED** [review]
Cool, "it would be kind of hard right now" is good enough for me. 🛳

**Comment by adamsoffer** [comment]
> Cool, "it would be kind of hard right now" is good enough for me. 🛳

Awesome :) Looks like circleci is failing again? Error is not too descriptive. hmm

**Comment by iameli** [comment]
Dunno, I'll look into it. I'm getting this when I `yarn install` locally:

```
@livepeer/livepeer.com: @sanity/core not installed in current project
@livepeer/livepeer.com: Project-specific commands not available until you run `sanity install`
@livepeer/livepeer.com: Error: "build" is not available outside of a Sanity project context.
@livepeer/livepeer.com: Run the command again within a Sanity project directory, where "@sanity/core"
@livepeer/livepeer.com: is installed as a dependency.
@livepeer/livepeer.com:     at C.runCommand (~/code/livepeerjs/node_modules/@sanity/cli/bin/sanity-cli.js:3452:1755)
@livepeer/livepeer.com:     at t.exports (~/code/livepeerjs/node_modules/@sanity/cli/bin/sanity-cli.js:2088:2289)
@livepeer/livepeer.com: error Command failed with exit code 1.
@livepeer/livepeer.com: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@livepeer/livepeer.com: npm ERR! code ELIFECYCLE
@livepeer/livepeer.com: npm ERR! errno 1
@livepeer/livepeer.com: npm ERR! @livepeer/livepeer.com@1.0.0-alpha.7 build-admin: `cd admin && yarn run build`
@livepeer/livepeer.com: npm ERR! Exit status 1
@livepeer/livepeer.com: npm ERR!
@livepeer/livepeer.com: npm ERR! Failed at the @livepeer/livepeer.com@1.0.0-alpha.7 build-admin script.
@livepeer/livepeer.com: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@livepeer/livepeer.com: npm ERR! A complete log of this run can be found in:
@livepeer/livepeer.com: npm ERR!     /Users/iameli/.npm/_logs/2020-03-19T01_58_25_763Z-debug.log
@livepeer/livepeer.com: ERROR: "build-admin" exited with 1.
@livepeer/livepeer.com: error Command failed with exit code 1.
```

Possible we need a `nohoist` on the sanity package...?

**Comment by adamsoffer** [comment]
> Possible we need a nohoist on the sanity package...?

Ah yeah let me check.

**Comment by adamsoffer** [comment]
@iameli confirmed I was missing a dependency. Doh. No issues running `yarn install` locally for me now. However, I'm seeing a circle-ci build-test error now.

**Comment by iameli** [comment]
Ah yeah, I've seen this before

```
@livepeer/explorer: $ npm run -s build:web
@livepeer/explorer: There might be a problem with the project dependency tree.
@livepeer/explorer: It is likely not a bug in Create React App, but something you need to fix locally.
@livepeer/explorer: The react-scripts package provided by Create React App requires a dependency:
@livepeer/explorer:   "webpack": "4.41.5"
@livepeer/explorer: Don't try to install it manually: your package manager does it automatically.
@livepeer/explorer: However, a different version of webpack was detected higher up in the tree:
@livepeer/explorer:   /home/circleci/repo/node_modules/webpack (version: 4.42.0) 
@livepeer/explorer: Manually installing incompatible versions is known to cause hard-to-debug issues.
@livepeer/explorer: If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
@livepeer/explorer: That will permanently disable this message but you might encounter other issues.
@livepeer/explorer: To fix the dependency tree, try following the steps below in the exact order:
@livepeer/explorer:   1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
@livepeer/explorer:   2. Delete node_modules in your project folder.
@livepeer/explorer:   3. Remove "webpack" from dependencies and/or devDependencies in the package.json file in your project folder.
@livepeer/explorer:   4. Run npm install or yarn, depending on the package manager you use.
@livepeer/explorer: In most cases, this should be enough to fix the problem.
@livepeer/explorer: If this has not helped, there are a few other things you can try:
@livepeer/explorer:   5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
@livepeer/explorer:      This may help because npm has known issues with package hoisting which may get resolved in future versions.
@livepeer/explorer:   6. Check if /home/circleci/repo/node_modules/webpack is outside your project directory.
@livepeer/explorer:      For example, you might have accidentally installed something in your home folder.
@livepeer/explorer:   7. Try running npm ls webpack in your project folder.
@livepeer/explorer:      This will tell you which other package (apart from the expected react-scripts) installed webpack.
@livepeer/explorer: If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
@livepeer/explorer: That would permanently disable this preflight check in case you want to proceed anyway.
@livepeer/explorer: P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
@livepeer/explorer: error Command failed with exit code 1.
@livepeer/explorer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thoughts on archiving the old explorer in a different repo? I dunno if we're still intending to support it at all.

**Comment by adamsoffer** [comment]
Yeah, good call. Let's archive it in a different repo along with the `apollo` package.

**Comment by adamsoffer** [comment]
@iameli I removed the `explorer` and `apollo` deps and fixed the ci-build 🎊

"Explorer Classic" now lives [here](https://github.com/livepeer/explorer-classic) and is all set up with automatic deploys to now from master branch.

**Comment by adamsoffer** [comment]
We can probably archive `graphql-sdk` and `chroma` deps as well at some point in favor of the `subgraph` and `livepeer-ui`.

**Comment by iameli** [comment]
I can't give another approval but with CI passing this can be merged. Already working off of it downstream.

**Pull request merged**
